name: Public to website
on:
  push:
    branches: [master]

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: deploy-${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            deploy-${{ runner.os }}-pip-
      - name: Generate post from jupyter notebook
        run: |
          cd website
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          python scripts/parse_notebook.py
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: deploy-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            deploy-${{ runner.os }}-node-
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: gh-pages
        run: |
          cd website
          git config --global user.email "zootopibot@gmail.com"
          git config --global user.name "ZootoPi bot"
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci --prefer-offline
          else
          npm i
          fi
          npm run deploy
