name: documentation

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Generate post from jupyter notebook
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          python scripts/parse_notebook.py
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Generate post from jupyter notebook
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          python scripts/parse_notebook.py
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: gh-pages
        run: |
          git config --global user.email "<41898282+github-actions[bot]@users.noreply.github.com>"
          git config --global user.name "github-actions[bot]"
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run deploy
